In [1]:
!pip install seaborn


[notice] A new release of pip is available: 23.0.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip


In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.distributions.uniform import Uniform
from torch.utils.data import TensorDataset,DataLoader
import pandas as pd
import numpy as np



### Our basic Data
#### "RRR is  great Movie"
#### "mari is  great Movie"

In [12]:
inputs = torch.tensor([
    [1.,0.,0.,0.,0.],
    [0.,1.,0.,0.,0.],
    [0.,0.,1.,0.,0.],
    [0.,0.,0.,1.,0.],
    [0.,0.,0.,0.,1.]
])
labels = torch.tensor([
    [0.,1.,0.,0.,0.],
    [0.,0.,1.,0.,0.],
    [0.,0.,0.,1.,0.],
    [0.,0.,0.,0.,1.],
    [0.,1.,0.,0.,0.]
])
dataset =TensorDataset (inputs,labels)
dataloader =DataLoader(dataset)

In [29]:
class wordembeddingscarcth(nn.Module):
    def __init__(self):
        super().__init__()
        min_val=-0.5
        max_val =0.5
        self.input1_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input1_w2 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input2_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input2_w2 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input3_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input3_w2 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input4_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input4_w2 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input5_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.input5_w2 =nn.Parameter(Uniform(min_val,max_val).sample())

        self.output1_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output1_w2 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output2_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output2_w2 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output3_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output3_w2 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output4_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output4_w2 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output5_w1 =nn.Parameter(Uniform(min_val,max_val).sample())
        self.output5_w2 =nn.Parameter(Uniform(min_val,max_val).sample())

        self.loss = nn.CrossEntropyLoss()

    def forward(self,input):
        input= input[0]

        input_neuron1=(input[0]*self.input1_w1)+(input[1]*self.input2_w1)+(input[2]*self.input3_w1)+(input[3]*self.input4_w1)+(input[4]*self.input5_w1)
        input_neuron2=(input[0]*self.input1_w2)+(input[1]*self.input2_w2)+(input[2]*self.input3_w2)+(input[3]*self.input4_w2)+(input[4]*self.input5_w2)
        output1 = (input_neuron1*self.output1_w1)+(input_neuron2*self.output1_w2)
        output2 = (input_neuron1*self.output2_w1)+(input_neuron2*self.output2_w2)
        output3 = (input_neuron1*self.output3_w1)+(input_neuron2*self.output3_w2)
        output4 = (input_neuron1*self.output4_w1)+(input_neuron2*self.output4_w2)
        output5 = (input_neuron1*self.output5_w1)+(input_neuron2*self.output5_w2)

        output_presoftmax =torch.stack([output1,output2,output3,output4,output5])# we are useing .stack to keep our gradients
        return output_presoftmax
    def config_optimizer(self):
        return optim.Adam(self.parameters(),lr=0.1)
    def train_step(self,batch):
        input_i,label_i=batch
        output_i =self.forward(input_i)
        loss =self.loss(output_i,label_i[0])
        return loss

    

In [30]:
model = wordembeddingscarcth()
print("before optimiztiopn vals:")
for name,param in model.named_parameters():
    print(name,param.data)

before optimiztiopn vals:
input1_w1 tensor(-0.0710)
input1_w2 tensor(-0.4530)
input2_w1 tensor(-0.3859)
input2_w2 tensor(0.3674)
input3_w1 tensor(-0.4720)
input3_w2 tensor(-0.4113)
input4_w1 tensor(-0.4963)
input4_w2 tensor(-0.2643)
input5_w1 tensor(0.4704)
input5_w2 tensor(-0.0106)
output1_w1 tensor(-0.0262)
output1_w2 tensor(0.3142)
output2_w1 tensor(-0.4795)
output2_w2 tensor(-0.0813)
output3_w1 tensor(-0.2290)
output3_w2 tensor(-0.2076)
output4_w1 tensor(0.2759)
output4_w2 tensor(-0.3437)
output5_w1 tensor(0.3063)
output5_w2 tensor(-0.1833)


In [31]:
print("before trainig data")
data = {
    "w1":[
        model.input1_w1.item(),
        model.input2_w1.item(),
        model.input3_w1.item(),
        model.input4_w1.item(),
        model.input5_w1.item(),
    ],
    "w2":[
        model.input1_w2.item(),
        model.input2_w2.item(),
        model.input3_w2.item(),
        model.input4_w2.item(),
        model.input5_w2.item(),
    ],
    "word":["RRR","is","great","movie","mari"],
    "input":["ip1","ip2","ip3","ip4","ip5"]
}
df =pd.DataFrame(data)
df

before trainig data


w1        w2   word input
0 -0.070989 -0.453044    RRR   ip1
1 -0.385862  0.367398     is   ip2
2 -0.471974 -0.411343  great   ip3
3 -0.496322 -0.264252  movie   ip4
4  0.470363 -0.010594   mari   ip5

In [32]:
optimizer = model.config_optimizer()
num_epochs = 100
for epoch in range(num_epochs):
    epoch_loss=0
    for batch in dataloader:
        optimizer.zero_grad()
        loss =model.train_step(batch)
        loss.backward()
        optimizer.step()
        epoch_loss +=loss.item()
    print(f"{epoch+1}/num_epochs, Loss : {epoch_loss:.4f}")

print("done")


1/num_epochs, Loss : 8.6662
2/num_epochs, Loss : 7.4880
3/num_epochs, Loss : 6.5293
4/num_epochs, Loss : 5.4847
5/num_epochs, Loss : 4.3754
6/num_epochs, Loss : 3.3270
7/num_epochs, Loss : 2.4253
8/num_epochs, Loss : 1.7756
9/num_epochs, Loss : 1.3712
10/num_epochs, Loss : 1.0475
11/num_epochs, Loss : 0.7063
12/num_epochs, Loss : 0.3819
13/num_epochs, Loss : 0.1802
14/num_epochs, Loss : 0.0971
15/num_epochs, Loss : 0.0638
16/num_epochs, Loss : 0.0469
17/num_epochs, Loss : 0.0367
18/num_epochs, Loss : 0.0299
19/num_epochs, Loss : 0.0252
20/num_epochs, Loss : 0.0217
21/num_epochs, Loss : 0.0191
22/num_epochs, Loss : 0.0171
23/num_epochs, Loss : 0.0155
24/num_epochs, Loss : 0.0142
25/num_epochs, Loss : 0.0131
26/num_epochs, Loss : 0.0121
27/num_epochs, Loss : 0.0113
28/num_epochs, Loss : 0.0106
29/num_epochs, Loss : 0.0100
30/num_epochs, Loss : 0.0094
31/num_epochs, Loss : 0.0089
32/num_epochs, Loss : 0.0085
33/num_epochs, Loss : 0.0080
34/num_epochs, Loss : 0.0076
35/num_epochs, Loss : 0

In [33]:
print("After trainig data")
data = {
    "w1":[
        model.input1_w1.item(),
        model.input2_w1.item(),
        model.input3_w1.item(),
        model.input4_w1.item(),
        model.input5_w1.item(),
    ],
    "w2":[
        model.input1_w2.item(),
        model.input2_w2.item(),
        model.input3_w2.item(),
        model.input4_w2.item(),
        model.input5_w2.item(),
    ],
    "word":["RRR","is","great","movie","mari"],
    "input":["ip1","ip2","ip3","ip4","ip5"]
}
df =pd.DataFrame(data)
df

After trainig data


w1        w2   word input
0 -2.290022 -1.883055    RRR   ip1
1 -2.334228  2.088861     is   ip2
2  1.955957 -3.115977  great   ip3
3  2.567624  1.669730  movie   ip4
4 -2.146554 -1.878703   mari   ip5

### Checking our prediction

In [36]:
softmax =nn.Softmax(dim=0)
print(torch.round(softmax(model(torch.tensor([[1.,0.,0.,0.,0.]])))))
print(torch.round(softmax(model(torch.tensor([[0.,1.,0.,0.,0.]])))))
print(torch.round(softmax(model(torch.tensor([[0.,0.,1.,0.,0.]])))))

tensor([0., 1., 0., 0., 0.], grad_fn=<RoundBackward0>)
tensor([0., 0., 1., 0., 0.], grad_fn=<RoundBackward0>)
tensor([0., 0., 0., 1., 0.], grad_fn=<RoundBackward0>)


### conclusion

#### our conclusion is simple after trainnig our data is prediction correct next values and commabining the simmilar tokens like "RRR" & "mari"